#!/usr/bin/env bash
# Script that pings an IP address passed as an argument, $1 being the 1st argument (ip address) and ping -c 5 sends 5 packets and listens for the responses
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
